const indianStates = [
  { id: 1, name: "Andhra Pradesh", image: "../assets/tourist/tourist/Andhra Pradesh.jpg" },
  { id: 2, name: "Arunachal Pradesh", image: "https://source.unsplash.com/featured/?ArunachalPradesh" },
  { id: 3, name: "Assam", image: "../assets/tourist/tourist/assam.jpg" },
  { id: 4, name: "Bihar", image: "https://source.unsplash.com/featured/?Bihar" },
  { id: 5, name: "Chhattisgarh", image: "https://source.unsplash.com/featured/?Chhattisgarh" },
  { id: 6, name: "Goa", image: "https://source.unsplash.com/featured/?Goa" },
  { id: 7, name: "Gujarat", image: "https://source.unsplash.com/featured/?Gujarat" },
  { id: 8, name: "Haryana", image: "https://source.unsplash.com/featured/?Haryana" },
  { id: 9, name: "Himachal Pradesh", image: "https://source.unsplash.com/featured/?HimachalPradesh" },
  { id: 10, name: "Jharkhand", image: "https://source.unsplash.com/featured/?Jharkhand" },
  { id: 11, name: "Karnataka", image: "https://source.unsplash.com/featured/?Karnataka" },
  { id: 12, name: "Kerala", image: "https://source.unsplash.com/featured/?Kerala" },
  { id: 13, name: "Madhya Pradesh", image: "https://source.unsplash.com/featured/?MadhyaPradesh" },
  { id: 14, name: "Maharashtra", image: "https://source.unsplash.com/featured/?Maharashtra" },
  { id: 15, name: "Manipur", image: "https://source.unsplash.com/featured/?Manipur" },
  { id: 16, name: "Meghalaya", image: "https://source.unsplash.com/featured/?Meghalaya" },
  { id: 17, name: "Mizoram", image: "https://source.unsplash.com/featured/?Mizoram" },
  { id: 18, name: "Nagaland", image: "https://source.unsplash.com/featured/?Nagaland" },
  { id: 19, name: "Odisha", image: "https://source.unsplash.com/featured/?Odisha" },
  { id: 20, name: "Punjab", image: "https://source.unsplash.com/featured/?Punjab" },
  { id: 21, name: "Rajasthan", image: "https://source.unsplash.com/featured/?Rajasthan" },
  { id: 22, name: "Sikkim", image: "https://source.unsplash.com/featured/?Sikkim" },
  { id: 23, name: "Tamil Nadu", image: "https://source.unsplash.com/featured/?TamilNadu" },
  { id: 24, name: "Telangana", image: "https://source.unsplash.com/featured/?Telangana" },
  { id: 25, name: "Tripura", image: "https://source.unsplash.com/featured/?Tripura" },
  { id: 26, name: "Uttar Pradesh", image: "https://source.unsplash.com/featured/?UttarPradesh" },
  { id: 27, name: "Uttarakhand", image: "https://source.unsplash.com/featured/?Uttarakhand" },
  { id: 28, name: "West Bengal", image: "https://source.unsplash.com/featured/?WestBengal" },
  { id: 29, name: "Delhi", image: "https://source.unsplash.com/featured/?Delhi" },
];

export { indianStates };
