const famousIndianTemples = [
  {
    id: 1,
    name: "Kedarnath Temple",
    description: "One  Jyotirlingas  Lord Shiva, situated in the Himalayas.",
    location: "Kedarnath",
    state: "Uttarakhand",
    img: "https://cdn.tourmyindia.com/blog/wp-content/uploads/2018/04/Kedarnath-Temple.jpg",
  },
  {
    id: 2,
    name: "Meenakshi Amman Temple",
    description: "A historic temple in Tamil Nadu dedicated to Goddess Meenakshi and Lord Shiva.",
    location: "Madurai",
    state: "Tamil Nadu",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Madurai_Meenakshi_Temple_1.jpg/1280px-Madurai_Meenakshi_Temple_1.jpg",
  },
  {
    id: 3,
    name: "Ramanathaswamy Temple",
    description: "Famous for its longest corridor, one of the twelve Jyotirlingas in Rameswaram.",
    location: "Rameswaram",
    state: "Tamil Nadu",
    img: "https://www.tamilnadutourism.tn.gov.in/img/pages/large-desktop/ramanathaswamy-temple-1653989971_49.jpg",
  },
  {
    id: 4,
    name: "Mahakaleshwar Temple",
    description: "A sacred Jyotirlinga in Ujjain, known for its Bhasma Aarti ritual.",
    location: "Ujjain",
    state: "Madhya Pradesh",
    img: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Mahakaleshwar_Temple%2C_Ujjain.jpg",
  },
  {
    id: 5,
    name: "Golden Temple (Harmandir Sahib)",
    description: "The holiest Sikh shrine, known for its golden architecture and serene Amrit Sarovar.",
    location: "Amritsar",
    state: "Punjab",
    img: "https://www.sikhnet.com/files/styles/square_medium_200px/public/Golden-Temple-Amritsar-Punjab.jpg",
  },
  {
    id: 6,
    name: "Brihadeeswarar Temple",
    description: "A UNESCO World Heritage Site, built by the Chola dynasty, dedicated to Lord Shiva.",
    location: "Thanjavur",
    state: "Tamil Nadu",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Thanjavur_Brihadeeswara_Temple_tower_2010.jpg/800px-Thanjavur_Brihadeeswara_Temple_tower_2010.jpg",
  },
  {
    id: 7,
    name: "Siddhivinayak Temple",
    description: "One of Mumbai's most famous temples, dedicated to Lord Ganesha.",
    location: "Mumbai",
    state: "Maharashtra",
    img: "https://cdn.s3waas.gov.in/s3e16b2b5e3b3fcdfdd3af7a3a3afdc1fc/uploads/bfi_thumb/2022080587-olwje69qvneqlt82cctpj1n8onrk3r38mwrh0eggyg.jpg",
  },
  {
    id: 8,
    name: "Akshardham Temple",
    description: "A modern architectural marvel showcasing India's ancient art and culture.",
    location: "New Delhi",
    state: "Delhi",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Akshardham_Delhi.jpg/1024px-Akshardham_Delhi.jpg",
  },
  {
    id: 9,
    name: "Jagannath Temple",
    description: "A key Char Dham pilgrimage site, famous for the Rath Yatra festival.",
    location: "Puri",
    state: "Odisha",
    img: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Jagannath_Temple_Puri.jpg",
  },
  {
    id: 10,
    name: "Vaishno Devi Temple",
    description: "A highly revered shrine dedicated to Goddess Vaishno Devi.",
    location: "Katra",
    state: "Jammu & Kashmir",
    img: "https://www.templepurohit.com/wp-content/uploads/2015/12/Vaishno-Devi-Temple-Katra-Jammu-Kashmir.jpg",
  },
  {
    id: 11,
    name: "Somnath Temple",
    description: "One of the twelve Jyotirlingas, repeatedly rebuilt after invasions.",
    location: "Prabhas Patan",
    state: "Gujarat",
    img: "https://www.gujarattourism.com/content/dam/gujrattourism/images/temples/somnath-temple.jpg",
  },
  {
    id: 12,
    name: "Kamakhya Temple",
    description: "A revered Shakti Peetha, dedicated to Goddess Kamakhya in Assam.",
    location: "Guwahati",
    state: "Assam",
    img: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Kamakhya_Temple_top_view.jpg",
  },
  {
    id: 13,
    name: "Lingaraj Temple",
    description: "An ancient temple in Odisha, dedicated to Lord Shiva.",
    location: "Bhubaneswar",
    state: "Odisha",
    img: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Lingaraja_Temple_Bhubaneswar.jpg",
  },
  {
    id: 14,
    name: "Dilwara Temples",
    description: "Exquisite Jain temples in Mount Abu, known for their intricate marble carvings.",
    location: "Mount Abu",
    state: "Rajasthan",
    img: "https://upload.wikimedia.org/wikipedia/commons/1/15/Dilwara_Temples_2.JPG",
  },
  {
    id: 15,
    name: "Tirupati Balaji Temple",
    description: "One of the richest temples in India, dedicated to Lord Venkateswara.",
    location: "Tirumala",
    state: "Andhra Pradesh",
    img: "https://www.templepurohit.com/wp-content/uploads/2016/05/Tirupati-Balaji.jpg",
  },
];

export { famousIndianTemples };
